### ISSUE TITLE
provide config as object instead of string

### ISSUE THREAD

**Issue by joh-klein** [nelsyeung/usemin#1]
How do you feel about providing the UglifyJS, CleanCSS and HTML minifier config options directly as an object to usemin() instead of as a string to another file? I don't mean as a replacement but as another way.

**Comment by nelsyeung** [comment]
This actually sounds quite good. I guess we could have the `configFile` option alongside with a new `config` option which will override any settings set in the config file when both options are set. I will do this tonight (if I'm free), unless you want to implement it.

**Comment by nelsyeung** [comment]
I've added this, so now you can do something like:

```js
usemin('src/index.html', 'dist', {
  output: 'dist/index.html',
  htmlmin: true,
  removeLivereload: true,
  config: {
    uglifyjs: {
    },
    cleancss: {
    },
    htmlminifier: {
      removeComments: false,
      collapseWhitespace: false,
      removeEmptyAttributes: false,
      removeScriptTypeAttributes: false,
      removeStyleLinkTypeAttributes: false,
      minifyJS: false,
      minifyCSS: false,
    }
  }
});
```

Do you mind testing this as well before I publish? Thanks!

**Comment by joh-klein** [comment]
Looks fine to me. Does what I was hoping it would. Thanks!

**Comment by nelsyeung** [comment]
Thanks for testing! v0.5.0 has been published.
