### ISSUE TITLE
calling uglifyjs/cleanss with false should just concatenate

### ISSUE THREAD

**Issue by joh-klein** [nelsyeung/usemin#2]
What I would find super helpful is, if my config object looked like this:
```
config: {
  uglifyjs: false,
  cleancss: false,
  htmlminifier: false
}
```
It would only concatenate all JS and CSS files and wouldn't do any html minifying (could even do this instead of the extra param `htmlmin: false`).  I get why `uglifyjs: {}` uses the default option of that tool, that is a sensible default. But in my case, I am basically only using usemin to reduce all external libs to one `libs.min.js`. And these files are already in a minified state (e.g. `angular.min.js`, `moment.min.js`).

**Comment by nelsyeung** [comment]
Sorry for this late reply, I'm current on a trip.

I feel that this additional complexity will only improve performance slightly. https://github.com/mishoo/UglifyJS2/issues/321 has already introduced speeding up on already minified files so I don't think it matters that much. In addition, UglifyJS already has a simple config `compress: false` to not compress files, thus I rather just keep it simple and let users pass configs to the respective packages. If the project is that large I recommend using other build tools anyway.
