### ISSUE TITLE
ES6 code throws error with uglify-js

### ISSUE THREAD

**Issue by joh-klein** [nelsyeung/usemin#3]
Since uglify-js is [not yet ready](https://github.com/mishoo/UglifyJS2/issues/448) with their version that understands ES6, it would be great if you would either implement something along the lines of my idea in #2 or add another step for babel to transpile the ES >5 code.

**Comment by nelsyeung** [comment]
I feel that if you require ES6 it's best to use a proper build chain as there are lots of complications. You can always compile stuff to ES5 first using babel then use usemin.

However, I am actually thinking of making a full fledged CLI build tool that doesn't require configurations or as complicated as Webpack.
